# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: linux
  pool:
    vmImage: "ubuntu-latest"
  strategy:
    matrix:
      linux_py36_limix2:
        python.version: '3.6'
        limix.version: '<3,>=2'
      linux_py36_limix3:
        python.version: '3.6'
        limix.version: '>=3'
      linux_py37_limix3:
        python.version: '3.7'
        limix.version: '>=3'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - script: python -m pip install setuptools numpy scipy -U
    displayName: 'Pre-installation dependencies'
  - script: python -m pip install "limix $(limix.version)"
    displayName: 'Install limix'
  - script: python -c "import sys; import limix; sys.exit(limix.test())"
    displayName: 'Test limix'

- job: macos
  pool:
    vmImage: "macos-10.13"
  strategy:
    matrix:
      mac_py37:
        python.version: '3.7'
        limix.version: '>=3'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - script: python -m pip install setuptools numpy scipy -U
    displayName: 'Pre-installation dependencies'
  - script: python -m pip install "limix $(limix.version)"
    displayName: 'Install limix'
  - script: python -c "import sys; import limix; sys.exit(limix.test())"
    displayName: 'Test limix'

- job: windows
  pool:
    vmImage: "vs2017-win2016"
  strategy:
    matrix:
      windows_py37:
        python.version: '3.7'
        limix.version: '>=3'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - script: python -m pip install setuptools numpy scipy -U
    displayName: 'Pre-installation dependencies'
  - script: python -m pip install "limix $(limix.version)"
    displayName: 'Install limix'
  - script: python -c "import sys; import limix; sys.exit(limix.test())"
    displayName: 'Test limix'